### ISSUE TITLE
[BUG] Embeddable list of nested object cannot be saved

### ISSUE THREAD

**Issue by m4ttek** [eclipse/jnosql#460] opened 2023-12-06 11:44 UTC
### Which JNoSQL project the issue refers to?

JNoSQL (Core)

### Bug description

There seems to be a problem with a list of nested objects in an Entity;
![image](https://github.com/eclipse/jnosql/assets/6191860/955e7113-01cf-4ffe-875f-c85a1e4d0608)

A list is treated as a single document? It worked well on 1.0.2 version.

### JNoSQL Version

1.0.3

### Steps To Reproduce

1. Create an entity
2. Create an embeddable entity
3. Use an embeddable entity in main entity within a collection of objects.
4. Try to save this entity.

**Comment by otaviojava** [comment] 2023-12-06 13:15
@m4ttek could you give an entity sample to test and also create a test scenario?

**Comment by m4ttek** [comment] 2023-12-06 13:29
Yes, it isn't even a test scenario, but a test initialization ;)

There is a main entity which contains nested `availableTransitions`:

```
import com.arangodb.serde.InternalId;
import com.arangodb.serde.InternalKey;
import jakarta.annotation.Nullable;
import jakarta.nosql.Column;
import jakarta.nosql.Entity;
import jakarta.nosql.Id;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.sages.ssop.workflow.domain.component.ComponentType;
import pl.sages.ssop.workflow.domain.transition.Transition;
import pl.sages.ssop.workflow.infrastructure.database.index.Index;

@Builder
@Entity(COLLECTION_NAME)
@Data
@NoArgsConstructor
@AllArgsConstructor
public final class WorkflowStep {

    public static final String COLLECTION_NAME = "workflow_steps";

    @InternalId
    @Id
    private String id;
    @InternalKey
    @Column("_key")
    private String key;

    @Column
    @NotNull
    @Index
    private String workflowSchemaKey;

    @Column
    @NotNull
    private String stepName;

    @Column
    @NotNull
    private MainStepType mainStepType;

    @Column
    @Nullable
    private Integer stepNo;

    @Column
    @Nullable
    private ComponentType componentName;

    @Column
    @Nullable
    @Index
    private String componentConfigurationKey;

    @Column
    @Nullable
    @Index
    private String relationTypeKey;

    @Column
    @Nullable
    private List<Transition> availableTransitions;
}
```

There is a Transition embeddable entity:
```
import jakarta.annotation.Nullable;
import jakarta.nosql.Column;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.eclipse.jnosql.mapping.Embeddable;

@Embeddable
@Data
@NoArgsConstructor
@AllArgsConstructor
public final class Transition {

    @Column
    @NotNull
    private String targetWorkflowStepKey;
    @Column
    @NotNull
    private StepTransitionReason stepTransitionReason;
    @Column
    @Nullable
    private String mailTemplateKey;
    @Column
    @NotNull
    private List<String> restrictedRoleGroups;
}
```

and there is my method which tries to initalize collection with example entity:

```
    @BeforeEach
    void saveTestingStep(SeContainer seContainer) {
        var workflowStep = WorkflowStep.builder()
                .key(TEST_WORKFLOW_STEP_KEY)
                .workflowSchemaKey(TEST_WORKFLOW_SCHEMA_KEY)
                .mainStepType(MainStepType.ENTRY)
                .stepNo(1)
                .availableTransitions(List.of(new Transition(TEST_WORKFLOW_STEP_KEY, REPEAT, null, List.of("ADMIN"))))
                .build();
        this.testWorkflowStep = seContainer.select(WorkflowStepRepository.class).get().save(workflowStep);
    }
```

**Comment by otaviojava** [comment] 2023-12-06 13:44
hum, that might be related with allow null values. 
Anyway I will work on it.

**Comment by otaviojava** [comment] 2023-12-06 16:46
@m4ttek could you give the stack trace?

I also created the entity for the test:
Could you check if that is your entity: 
https://github.com/eclipse/jnosql/pull/461

I cannot reproduce your issues.

**Comment by otaviojava** [comment] 2023-12-06 17:20
Thank you, this is at the arangoDB driver side, I will create a code to that side.

**Comment by otaviojava** [comment] 2023-12-06 19:35
Thank you. I updated the structure to allow null values,; we can use it:

https://github.com/eclipse/jnosql-databases/pull/255/files

**Comment by otaviojava** [comment] 2023-12-06 20:01
This seams a critical bug, @m4ttek could you test the snapshot version?
If yes, I will release a new version with this fix.

**Comment by m4ttek** [comment] 2023-12-07 10:18
Ok, unfortunately, there is another test case failing:

```
        var secondWorkflowStep = WorkflowStep.builder()
                .workflowSchemaKey(TEST_WORKFLOW_SCHEMA_KEY)
                .stepName("Second testing step")
                .stepNo(null)
                .mainStepType(MainStepType.IN_PROGRESS)
                .build();
        secondWorkflowStep = workflowStepRepository.save(secondWorkflowStep);
```

It looks like it doesn't handle nullable embeddable lists properly:

```
WARNING: Internal server error
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "embeddable" is null
	at org.eclipse.jnosql.mapping.document.FieldConverter$3.convert(FieldConverter.java:89)
	at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.lambda$feedObject$5(DocumentEntityConverter.java:158)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.convertEntity(DocumentEntityConverter.java:221)
	at org.eclipse.jnosql.mapping.document.DocumentEntityConverter.toEntity(DocumentEntityConverter.java:106)
	at org.eclipse.jnosql.mapping.document.DefaultDocumentEntityConverter$Proxy$_$$_WeldClientProxy.toEntity(Unknown Source)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.lambda$persist$8(AbstractDocumentTemplate.java:269)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.persist(AbstractDocumentTemplate.java:271)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.insert(AbstractDocumentTemplate.java:82)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by otaviojava** [comment] 2023-12-07 14:19
Yeap, now we need to whole cases for nullable values.

**Comment by otaviojava** [comment] 2023-12-08 10:11
Thank you, @m4ttek please test and give me more cases.

**Comment by m4ttek** [comment] 2023-12-08 10:40
@otaviojava I've tested the new version, and now we have another problem. It seems like I cannot insert a new record without providing the key explicitly. 

Test case is the same:
```
        var secondWorkflowStep = WorkflowStep.builder()
                .workflowSchemaKey(TEST_WORKFLOW_SCHEMA_KEY)
                .stepName("Second testing step")
                .stepNo(null)
                .mainStepType(MainStepType.IN_PROGRESS)
                .build();
        secondWorkflowStep = workflowStepRepository.save(secondWorkflowStep);
```

And it ends with the following exception and stack trace:
```
com.arangodb.ArangoDBException: Response: 400, Error: 1221 - illegal document key
	at com.arangodb.ArangoDBException.of(ArangoDBException.java:137)
	at com.arangodb.ArangoDBException.of(ArangoDBException.java:111)
	at com.arangodb.ArangoDBException.of(ArangoDBException.java:107)
	at com.arangodb.internal.net.CommunicationProtocol.execute(CommunicationProtocol.java:43)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:55)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:43)
	at com.arangodb.internal.ArangoExecutorSync.execute(ArangoExecutorSync.java:39)
	at com.arangodb.internal.ArangoCollectionImpl.insertDocument(ArangoCollectionImpl.java:55)
	at org.eclipse.jnosql.databases.arangodb.communication.DefaultArangoDBDocumentManager.insert(DefaultArangoDBDocumentManager.java:68)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.lambda$new$0(AbstractDocumentTemplate.java:65)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.persist(AbstractDocumentTemplate.java:271)
	at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.insert(AbstractDocumentTemplate.java:82)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at org.eclipse.jnosql.databases.arangodb.mapping.ArangoDBTemplate$_$$_WeldClientProxy.insert(Unknown Source)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepository.save(AbstractDocumentRepository.java:56)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.lambda$invoke$0(AbstractDocumentRepositoryProxy.java:51)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.unwrapInvocationTargetException(AbstractDocumentRepositoryProxy.java:100)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.invoke(AbstractDocumentRepositoryProxy.java:51)
	at jdk.proxy3/jdk.proxy3.$Proxy159.save(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.lambda$invoke$0(AbstractDocumentRepositoryProxy.java:51)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.unwrapInvocationTargetException(AbstractDocumentRepositoryProxy.java:100)
	at org.eclipse.jnosql.mapping.document.query.AbstractDocumentRepositoryProxy.invoke(AbstractDocumentRepositoryProxy.java:51)
	at org.eclipse.jnosql.databases.arangodb.mapping.ArangoDBDocumentRepositoryProxy.invoke(ArangoDBDocumentRepositoryProxy.java:106)
	at jdk.proxy3/jdk.proxy3.$Proxy159.save(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at pl.sages.ssop.workflow.infrastructure.repositories.WorkflowStepRepository$_$$_WeldClientProxy.save(Unknown Source)
```

**Comment by m4ttek** [comment] 2023-12-10 16:25
@otaviojava I've checked the latest version and it seems to be working now :)

**Comment by otaviojava** [comment] 2023-12-10 19:24
Thank you!!!

**Comment by otaviojava** [comment] 2023-12-10 19:24
Closing once we fixed this one.

**Closed by otaviojava** 2023-12-10 19:24 UTC
Labels: bug
